### ISSUE TITLE
Questions about new API

### ISSUE THREAD

**Issue by ivan-kleshnin** [cyclejs/cycle-core#125]
I'm updating CycleJS examples and trying out new CycleJS API after some break.

First, I'm excited about it's simplicity. It's really the best of all previous attempts. At least by API metrics. All those imperative injections are implicit now. This is great!

I have a couple of questions though. 

1) I remember someone were asking @staltz in gitter (or maybe it was his monolog, I can't find) that it's possible to make injections automatic (like they are now). It was before(!) the Stream version came. 
There were even the same `Computer` and `User` terms mentioned. But that time Andre was negative about this auto-injection feature. If I remembered that correctly, I'm curious to know about those concerns. Did they prove itself invalid or something?

2) It's obvious that App structure is very close to Component structure. They accept interactions and optional props. Every app can (and probably should) be viewed as potential Web Component.

```js
function Computer(interactions) {
  ...
  return Observable.combineLatest(
    $firstName, $lastName,
    function (firstName, lastName) {
      return (
        <div>
          ...
          <footer key="footer"/>
        </div>
      );
    });
}

function Footer(interactions, props) {
  return {
    vtree$: Observable.return(
      <div>=== footer ===</div>
    )
  };
}

Cycle.registerCustomElement("footer", Footer);

Cycle.applyToDOM("#main", Computer);
```

What messes things up is their return values. Components may return some interactions that's why `vtree$` key is required but what about Apps? I didn't inspect WebComponents question thoroughly yet. Are they meant to be totally independent. And, if not, how then app should expose it's interactions to the outside space?

3) Do I get the newest data-flow schemes right? (`<-` below means reactive dependencies)

#### Simplest scheme
```
Computer: interactions <- VDOM
User: VDOM <- interactions (this part is implicit)
```

#### Advanced scheme
```
Intent: interactions <- intentions
Model: intentions <- models (this part is not very nice in naming aspect)
View: models <- VDOM
User: VDOM <- interactions (this part is implicit)
```

**Comment by staltz** [comment]
> 1) I remember someone said to @staltz in gitter (or maybe it was his monolog, I can't find) that it's possible to make injections automatic (like they are now). It was long before the Stream version came. 
There were even the same Computer and User terms mentioned. But that time Andre was negative about this auto-injection feature. If I remembered that correctly, I'm curious to know about those concerns. Did they prove itself invalid or something?

I can't remember precisely this discussion. I remember something related to automatic injection based on names, which I didn't like that much because smells like framework magic. Can you link me to the discussion in gitter?

> 2) It's obvious that App structure is very close to Component structure. They accept interactions and optional props. Every app can (and probably should) be viewed as potential Web Component. But what messes things up is their return value. We still have this vtree$ key required. I asked about it before and there was an answer that it may change. From my shallow observations this should be possible

The default is that every function in the architecture should return an object, and the properties of this object are used by the upcoming adapters #116. That is, `vtree$` won't be a convention, it will be just what the DOM adapter will expect. In other words, the return property names depend on the adapters used.

That said, we can use smart shortcuts. If an Observable is returned instead of a plain object, we assume it to be `Observable<VTree>`, and then we can use it as you mentioned. This actually already works like this for the top-level `app` function given to `applyToDOM`, but should work also for custom elements, to keep consistency. But it is what it is: just a shortcut helper to avoid typing always `{vtree$: Observable...}`.

> 3) Do I get the newest data-flow schemes right?

Yes. And precise naming is still a bit open, but the important thing is that this is up to the app developer, it doesn't need to be a framework convention. You can use Intent-Model-View or Action-Store-View or Foo-Bar-Baz, etc

**Comment by ivan-kleshnin** [comment]
> I can't remember precisely this discussion. I remember something related to automatic injection based on names, which I didn't like that much because smells like framework magic. Can you link me to the discussion in gitter?

Manually looked since **2014** till **April **06 2015**. Bookmarked a lof of interesting links.
And did find those quote :wink: 
https://gitter.im/staltz/cycle?at=5522ac274ceaec8225f95419

@cgeorg asked:
> What I'm wondering is... is Cycle.createStream even needed?
If the rendering portion of Cycle internally uses the circular linking functionality, that can be used to close the loop

Looks like he forecasted the current state of the arts.

Thank you for the answers on 2) and 3). That's clear now.

**Comment by staltz** [comment]
Maybe I was stubborn and didn't see what he said. But I was also quite sure we needed circularly dependent Observables _besides_  the `interactions` case. I think it's cleaner for the framework if circularly dependent Observables are optional and are a separate library, rather than embedded into the library. That's what @erykpiast did with `cyclejs-stream`

**Comment by serapath** [comment]
>### Simplest scheme
>```
>Computer: interactions <- VDOM
>User: VDOM <- interactions (this part is implicit)
>```

>### Advanced scheme
>```
>Intent: interactions <- intentions
>Model: intentions <- models (this part is not very nice in naming aspect)
>View: models <- VDOM
>User: VDOM <- interactions (this part is implicit)
>```

Looks pretty interesting. How should i read this? Can you write that in javascript?
I watched a youtube video from @staltz and like the convention fro "streams" named as `streamName$` a lot.

The following might be completely confusing - I'm still trying to wrap my head around cycle. :-)

While I played around with some pseudo-javascript to get more familiar with the ideas behind cycle, I figured, that one return value might be too little.
* Maybe more than one user interacts with the same computer
* Maybe a backend system interacts with it too.
* Maybe "components" interact with each other

But there can only be one return value....

So maybe there should be 1 or more potential entries and 1 or more potential exits.
```js
module.exports = function ComputerComponent (entries$, exits$) {
 // ...
}
```

**Comment by staltz** [comment]
@serapath that is exactly what #116 is about and I'm almost done building it.

**Comment by serapath** [comment]
oh ok, cool. i'll check :-)
