### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by nickdima** [cyclejs/cycle-core#137]
Could be a good idea to maintain one?

**Comment by staltz** [comment]
How is this better than release notes on the release page?

**Comment by RangerMauve** [comment]
I like changelogs because they're a single file that I can reference for the entire history of a project. I guess the release notes are pretty good, but I don't think everybody things to look at them. Maybe have something in the readme that says something along the lines of "check the releases for changes"?

**Comment by staltz** [comment]
I'll consider this in my roadmap, but for now it isn't useful here in Github as an issue.
