### ISSUE TITLE
Is cycle-core really the core of the project?

### ISSUE THREAD

**Issue by matchu** [cyclejs/cycle-core#149]
Okay, it's late and I should be asleep at this point, but hear me out.

I really like what Cycle.js enables, but I think I've finally been able to articulate what's been bothering me: the architecture feels asymmetrical. Under our abstraction, our application has some major components that I'm sure you know well :)

1. The DOM driver emits events to the Intent.
2. The Intent emits action events to the Model.
3. The Model emits state change events to the View.
4. The View emits vtree change events to the DOM driver.

(I'm omitting the human because, while it's conceptually valuable, the DOM driver fully encapsulates the interaction with the human; anything that the driver encapsulates is irrelevant to me as I wire together my top-level components.)

This much could be trivially implemented with raw RxJs, if there weren't a loop at the end. Because of that loop, we need Cycle.js to help us bridge the gap, because setting up a cycle in RxJs requires ugly hacks that we'd rather have hidden from us.

So, because the loop happens at the driver, Cycle.js treats the driver—the component that interacts with the human—as a special case that's fundamentally different than business logic components, and wired together in a special way.

However, I'm not sure that this distinction is fair. From what I can tell, despite having special side-effecty semantics, the driver is functionally identical to any other component of our system: it takes observables as input, and returns observables as output.

Consider what happens when I rephrase the application data flow:

1. The Model emits state change events to the View.
2. The View emits vtree change events to the DOM driver.
3. The DOM driver emits events to the Intent.
4. The Intent emits action events to the Model.

From this perspective, the *model* is the special case where the graph's cycle arises. We could, as I understand it, change zero framework code and just start telling people to put their *models* into `run` where the drivers used to be, and chain the drivers inline in `main` like we used to do with models. It seems like drivers just ended up chosen as the special case because of how the framework evolved over time, and because the handful of drivers that exist now just so happen to have really simple inputs/outputs that don't require as much muxing as, say, the intent→model edge.

---

So, I'm not really sure what this observation means for the project. I think the conclusion I reach is that __the documentation is unclear about what the project actually *is*__: I assumed that all of these parts were incredibly interconnected, but they're really all very distinct. `cycle-core` is a small hack to help me include cycles in my RxJs graphs. `cycle-web` is a RxJs wrapper for the DOM. They play together very well in the larger architecture, but `cycle-web` isn't fundamentally a "Cycle driver" and can easily drop into *any* RxJs project, and `cycle-core` has nothing to do with Model-View-Intent design or any of the other stuff in its docs.

That is, **the Cycle.js docs aren't really about Cycle.js; they're about how you believe Cycle.js fits into a much larger picture**. The documentation isn't there to help me understand what Cycle.js does; it's a book on reactive web applications, and its code samples use some libraries that y'all wrote to address some common use cases.

**I wonder if maybe this means that `cycle-core` and `cycle-web` are incidental, and the architecture is the *true* core of the project.**

Here's my read on what you've built: Cycle is an architecture for reactive web applications: a set of ideas about how you should structure your app using RxJs. To help you out, it also provides some libraries to address common use cases: `cycle-web`, to interact with the DOM, and `cycle-run`, to help you resolve the loops in your program.

I read a bit of the issue history, and I'm really impressed with the work in #116 where y'all realized that most of the core architecture could already be implemented in raw RxJs, and stripped the framework *way* down. Very cool :D That's why I think the repo name doesn't make sense anymore: your core ideas aren't actually in here anymore. This library is incidental to the larger ideas. (I'm not exactly sold on `cycle-run` for it, but a name change to match the concept change would make a whole lot of sense at this point.)

(As a brief anecdote, I'm looking at building a Chrome extension with this architecture—srsly, these ideas are incredibly exciting—but, once I looked at what my drivers actually would *be* for interacting with the Chrome API, I'm not actually sure my graph *contains* any cycles. So, I might use `cycle-web` but not `cycle-core`. It's a surprisingly legitimate scenario. I wonder if this might even arise in web apps: if you interact with some remote data store, the cycle happens across network lines; the local part of the graph doesn't actually contain the nasty cycle that `cycle-core` enables you to produce.)

This post is rambly and it changed a lot from top to bottom—I was initially gonna propose the convention of making business logic just another driver and making `main` all about routing, but I think that misses the point: `cycle-core` isn't a framework for structuring my applications; it just wraps the ugly cycles. No need to bring any more complexity into that.

Cool. I'm gonna go to bed now. I hope you hear all the love behind this post, because I feel kinda weird coming in here out of nowhere and telling y'all what I think your project *really* is, but it's all because I'm really impressed with your ideas and I was literally in bed, almost asleep multiple times, but waking back up because I was having so much fun engaging with these concepts. Thanks for reading, friends—happy 4th! <3

**Comment by matchu** [comment]
(It also now occurs to me that this is sorta the path that Flux takes: it pretty much launched as an architecture with no batteries included, except for React—which is incredibly similar to `cycle-web`—and they eventually caved a built a dispatcher to handle the ugly parts—like how `cycle-core` handles the ugly parts of cyclical graphs. It'd be interesting to look at how similar the projects really are, and where you can borrow from each other… but now I'm realizing that I'm sleepy and of *course* you're thinking about Flux all the time, since it's pretty much *the* other functional architecture on people's minds right now. Don't mind me xP)

**Comment by staltz** [comment]
Hi @matchu, thanks for this post.

> In that sense, I think maybe the project just needs a bit more clarity in terms of what it even is. Here's my read: Cycle is an architecture for reactive web applications: a set of ideas about how you should structure your app using RxJs. To help you out, it also provides some libraries to address common use cases: cycle-web, to interact with the DOM, and cycle-run, to help you resolve the loops in your program.

Yep, you nailed it, that's exactly what Cycle is. I don't know if I should have phrased it like that also in the documentation site. Maybe I should consider. But it didn't come to me as a surprise. In the early pre-Cycle days, I wrote [this blog post](http://futurice.com/blog/reactive-mvc-and-the-virtual-dom) about MVI, and my conclusion was:

>Model-View-Intent might evolve into a framework, or might not require enough boilerplate to justify a framework.
> (...)
>Another crucial tool is RxJS, which makes it possible to avoid writing low-level event utilities that other frameworks have to provide. It often almost removes the need to have a framework in the first place.

This was written almost a year ago and it's still accurate.

- - -

> cycle-core isn't a framework for structuring my applications; it just wraps the ugly cycles. No need to bring any more complexity into that.

Cycle Core is small, and the drivers are just utilities (essentially single-function libraries), but does that in itself mean Cycle (the constellation of utilities) isn't a framework? I see "framework" as a container where you place your business logic in, and you get a working application from that. Also from [Wikipedia](https://en.wikipedia.org/wiki/Software_framework), there is this:

> Frameworks contain key distinguishing features that separate them from normal libraries:
> - inversion of control: In a framework, unlike in libraries or normal user applications, the overall program's flow of control is not dictated by the caller, but by the framework.
> - default behavior: A framework has a default behavior. This default behavior must be some useful behavior and not a series of no-ops.[citation needed]
> - extensibility: A framework can be extended by the user usually by selective overriding or specialized by user code to provide specific functionality.
> - non-modifiable framework code: The framework code, in general, is not supposed to be modified, while accepting user-implemented extensions. In other words, users can extend the framework, but should not modify its code.

Cycle ticks many of these boxes:
- [x] inversion of control: the cyclic flow is tied together inside Cycle.run()
- [ ] default behavior: I don't think so, but I doubt modern JS frameworks satisfy this one either.
- [x] extensibility: yes, with drivers.
- [x] non-modifiable framework code: yes, Cycle.run() stays untouched.

So it's not a traditional monolith JS framework, but it is a framework in the sense that it gives you a model/shape of how to make an app, and gives you tools for that. The [docs site](http://cycle.js.org/drivers.html#drivers-make-cyclejs-extensible) is coherent with this: 
> Cycle Core is a very small framework, and Cycle Web’s DOM Driver is available as an optional plugin for your app. This means it is simple to replace the DOM Driver with any other driver function providing interaction with the user.
> (...)
> As a framework, it cannot be compared to monoliths which have ruled web development in the recent years. Cycle.js itself is after all just a small tool and a convention to create reactive dialogues with the external world using RxJS Observables.

Also, it's useful to have this constellation of utilities to follow a convention so they can easily interop. This convention is also what makes Cycle be a framework. We could easily just call it a day, make a utility function for defining cyclic Observables, but then without a convention we would be constantly confused with how particular utilities work and how we can adapt them to fit nicely in our app. With Cycle as a framework, all utilities will adhere to a convention, removing boilerplate.

- - - 

> Consider what happens when I rephrase the application data flow:
> - The Model emits state change events to the View.
> - The View emits vtree change events to the DOM driver.
> - The DOM driver emits events to the Intent.
> - The Intent emits action events to the Model.
>I was initially gonna propose the convention of making business logic just another driver and making main all about routing

You **could** do that but I don't see the point. Model, View and Intent are your app's logic, while driver is just an adapter for read/write effects. It doesn't make sense to make `main()` be `intent(domDriver(view(state$)))` if `domDriver()` is a utility function which isn't part of your app's logic. But it does make sense to have `main()` be `view(model(intent(DOM)))` because all those 3 functions **are part** of your app.

The asymmetry is only with regard to side effects. `main()` is pure, but a driver function is side-effectful. **However**, in the ideal magical world where you have `computer()` and `human()`, **both** are pure functions and it doesn't matter if you tie them as `computer(human(x))` or as `human(computer(x))`.

The other reason why drivers are treated differently is because you might have multiple drivers, but you have only one `main()`, when calling `Cycle.run()`. In a dialogue abstraction, this would be analogous to `main()` being interviewed by multiple reporters, because all the reporters interact with `main()`, and the `main()` answers back to those reporters, but there isn't any interaction between reporters.

**Comment by staltz** [comment]
Regarding Flux: the biggest complication I see is that people mistake "Flux" for "unidirectional data flow". Flux is only **one** implementation of unidirectional data flow. 

It's kind of like someone invented a bicycle, which is a wheeled-vehicle, and then someone else invents a car, and they start calling the car a *bicycle*, just because it has wheels and you can steer it. That's as far as similarities go: they have wheels and you can steer them. Calling a bicycle a car is silly, and vice-versa.

I did not take inspiration from Flux, neither was I mindful of potential similarities between Cycle and Flux. I just did my own thing: which was focus as much as possible on the power of RxJS Observables, staying true to my blog post: 

> Another crucial tool is RxJS, which makes it possible to avoid writing low-level event utilities that other frameworks have to provide. It often almost removes the need to have a framework in the first place.

RxJS is a utility for events. But was is an event? It's "something that happens". Well, what in your program cannot be an event then? That was my reasoning. Cycle went through multiple iterations. I started with the idea of a "Backward Function" (yes, a funny name), which then got renamed to DataFlowNode, these were Observable-in/Observable-out entities with cyclic dependency built-in. And as it sounds, they weren't that ergonomical. Then we made streams, which was a subclass of Observable, with cyclic-dependency built-in. Then we moved cyclic dependencies into Cycle.run(), so you can work with normal Observables, and that was it. To keep the purity of input/output semantics of functions, you end up having only one direction: in => out. That's the "unidirectional data flow". Unidirectionality together with interaction led to in => out => in, which is `x = computer(human(x))`. And that's Cycle.js. Not a single moment did I take any idea from Flux (I'm not even that much into reading resources about Flux, so I doubt I unconsciously copied them either).

There are a lot of things in Science which are not inventions. They are discoveries. A circle could have been independently discovered by mutually exclusive civilizations as the optimal shape for a wheel. There aren't many creative ways of discovering a simple and minimal solution to a problem.

Another unidirectional architecture is that in [Elm](https://github.com/evancz/elm-architecture-tutorial). It has signals, it has a loop, it has Model, View, and actions.

Are Cycle.js, Elm, and Flux all the same?
No, they are vehicles, they all have wheels, they can be steered, and they take you to places, but they aren't the same.

**Comment by jonrh** [comment]
Very good and informative by both. This put Cycle into better perspective for me. I think some of the key points here would do good in Cycle's documentation (FAQ, appendix or something).

**Comment by matchu** [comment]
Cool! Thanks for the replies, all :D 

I'll probably write a more thorough response tomorrow, but I think the major takeaway is that the documentation is super unclear on what `cycle-core` actually does: out of all the things an application developer must do to adhere to the Cycle architecture, exactly which of them does `cycle-core` do?

And I suspect that the docs are unclear on this point because `cycle-core` isn't really sure of its purpose yet: it seems to do the two unrelated jobs of hackily implementing graph cycles *and* helping me understand where my side effects are. Someone who needs to address one of these use cases might not actually need to address the other.

We should probably encapsulate those two jobs as their own modules, at least internally to the system, and, by better articulating how each part of the framework fits into the architecture, we might end up discovering an even better public API. I'm toying with a new API now, and I'll probably share tomorrow :)

**Comment by staltz** [comment]
> And I suspect that the docs are unclear on this point because cycle-core isn't really sure of its purpose yet: it seems to do the two unrelated jobs of gluing together graph cycles and helping me keep track of which components are side-effectful. 

Sorry, but Cycle Core has a very clear purpose, and those two jobs are not unrelated. `run()` is in my opinion perfect. Maybe you haven't seen it because the docs didn't make it clear to you.

**Comment by matchu** [comment]
Hmm, okay. In what way are those two jobs related, and what is Cycle Core's purpose? Is there a section of the docs I should re-read?

**Comment by staltz** [comment]
> and what is Cycle Core's purpose?

Cycle Core is `run()`. The purpose is to solve the circular dependency of Observables. `main`'s output is `request` (suppose for simplicity this is just one Observable), and `driver`'s output is `response` (suppose for simplicity this is also one Observable). What `run` does is make `response` depend on `request`, **and** `request` depend on `response`. It should be a **cycle**. I recommend watching this presentation where I explain the main ideas in Cycle.js, specially around 13:25 when I explain this cycle problem. 

Typically, whenever you have circularly dependent Observables, you need to implement that with a Subject, which isn't elegant because it's a mutable object, and you get some boilerplate. `run` allows you to code your app and forget about Subjects to solve cyclic dependencies.

That is the purpose of `run`: to solve the circular dependency of `y = main(x)` and `x = callDrivers(y)`. Actually I did explain this on the documentation site, on the frontpage. The fact that there is one `main` and there are multiple side effectful drivers isn't a secondary purpose, because it gives a shape to your applications. `run` doesn't even assume drivers are side effectful (they can perfectly be free of side effects too). 

> Is there a section of the docs I should re-read? Recently I've definitely just been jumping around; maybe I should sit down and give it another full read-through, now that my mental model is clearer…

I think I should update the docs of section "Observables", subsection "Observables in Cycle.js" to make run()'s purpose clearer.

> This makes me feel nervous and unwelcome

Don't worry, I rarely get angry over the internet, sorry if you got that impression. I must just be blunt, but sometimes I'm in a hurry to send the message.

**Comment by matchu** [comment]
Okay, yeah, that was the understanding I had. But, like, look at even that explanation: it breaks cycles, *and* gives shape to your application by separating the many drivers from the single app. The cycle-breaking and the module-organizing are two distinct features of the framework, but, in the docs and in the source code, those two features are all kinda mixed in with each other. Is there any fundamental connection between drivers and cycle-breaking? If not, the code could become more modular; it just smells weird to me that there's no function to run an *arbitrary* cyclical function pair.

So, yeah, cool. Glad the docs are gonna be clearer regarding Cycle Core's use cases :) That's probably the more important bit.

I'm still sitting around grappling with how putting drivers in the framework seems to make it harder to encapsulate my view/intent pairs. View and Intent feel more natural to me as a wrapper for their respective driver than for the single model, and it seems like, when multiple drivers are at play, there might be some nontrivial routing overhead, merging all the actions into model's input and broadcasting the state out of its output—is there a canonical example of that somewhere? `view(model(intent(event$)))` is beautiful, but I'm not sure how it generalizes to more intent/view pairs.

**Comment by staltz** [comment]
> If not, the code could become more modular; it just smells weird to me that there's no function to run an arbitrary cyclical function pair.

No it wouldn't become more modular. I recommend you try to do this split, and see how the outcome wouldn't make sense. I'm sorry, I explained this already and I feel like I'm repeating the same arguments if I try. `run()` doesn't have two unrelated purposes. Read the docs and watch the presentation, maybe that helps. Or try to split it as you said.

> Is there any fundamental connection between drivers and cycle-breaking?

It's not cycle-breaking. It's cycle building. And yes there is. Drivers need to be tied as a cycle with the main. It's like the fundamental connection between food and eating. You can split food and eating to make things more modular, that makes no sense.

**Comment by matchu** [comment]
I tried the split, and the result seems successful. I'll make it a bit more presentable and see what you make of it :)

**Comment by matchu** [comment]
Ahh yeah, I see what you're saying. Yeah, I understand that the Cycle architecture is about the communication between application code and driver code, and that this graph fundamentally contains a cycle. My question is something else: in order to enable this cycle, why does the framework need to control the edges surrounding the driver? These edges seem like they could be declared in the same way as the edge between Model and View, for example, but instead they're special-cased.

**Comment by staltz** [comment]
We have tried that already. in previous versions of cycle you could create drivers and tie them together with the application. it was cumbersome and had boilerplate. The other reason why drivers are a special cased is because drivers are not application code. The application programmer should only write application code. Driver code is assumed to just be there so you can just use it.

**Comment by matchu** [comment]
Huh, interesting. Even if it's not the direction Cycle takes, I'm really interested in pursuing an MVI architecture that allows me to better encapsulate View→Driver→Intent. If it ever looks presentable, I'll drop you a note :) Or, if it crashes and burns, I'll get to learn the same lessons as y'all firsthand. Thanks!

**Comment by matchu** [comment]
(Though really the reason I'm doing it is because I want reusable intent/view pairs *and* to be able to trivially hook them up to the model, and it's not clear to me how to do this under the current framework. If the docs ever get an example of this form, please lemme know :D)

**Comment by staltz** [comment]
Even though you closed this, may I ask? Why do you want to encapsulate View=>Driver=>Intent? And why can't it be done like this?

```js
// This is all inside one file

function intent(DOM) {
  return {
    increment$: DOM.get('.increment-button', 'click'),
    decrement$: DOM.get('.decrement-button', 'click')
  };
}

function view(state$) {
  // ...
  // ...
  return state$.flatMap(state =>
    // ...
    h('div', [
      h('button.increment-button', ...),
      h('button.decrement-button', ...)
    ])
  );
}

module.exports = {
  intent, view // both of them together encapsulated inside this module
}
```

**Comment by matchu** [comment]
Mhm. I think I'm still wondering about two things:

* What happens if I want to use more than one intent/view pair in an application? (Like, if I'm interfacing with both the DOM and with XHR?) I'm not super familiar with RxJs; is there a sane way to hook up multiple Intent→Model and Model→View edges, or maybe compose the many intents together into one intent?
* One of React's features is that a component can have its own state, distinct from the main app state, that just represent what the component is doing right now. For example, if I wanted to show a confirmation prompt before sending the delete action, I would keep that out of the model's concept of state and instead let the delete button component encapsulate it. Can a Cycle Intent and View coordinate with each other like that, without involving the model? Or is there a better canonical solution in Cycle?

**Comment by staltz** [comment]
Did you read about [custom elements](http://cycle.js.org/custom-elements.html)?

**Comment by matchu** [comment]
Yeah, but I don't think they're the general solution. What if I'm rendering the confirmation prompt through a Canvas driver, or I'm buffering the results of multiple responses from the XHR driver? If I want my interactions with an arbitrary driver to maintain state, do I need to re-engineer the driver to support something analogous to the DOM driver's custom elements?

**Comment by staltz** [comment]
With Rx you can easily maintain state and not even think about state. What is state after all? It's a mutable piece of data. That's not the paradigm with Rx. Instead, you just consider a timeline of events. "The current state" is just the last event that has happened.

**Comment by matchu** [comment]
Right. So, for the use case where I would reach for React's concept of state, what nodes and edges do I need to include in my Cycle graph instead?

It seems like the view/intent pair might want its own model, too, distinct from the application mode: the intent routes the event "click Delete on comment 1" to the internal model, which maps it to the state "comment 1 should include a deletion confirmation dialogue", which then feeds directly into the view.

So, I guess I answered my own question there: sounds like my `main` function needs to also include a reference to this other model, and route accordingly. Hmm, I wonder if there's a clean way to encapsulate *that*…

**Comment by staltz** [comment]
If you want to encapsulate MVI in some box, that's custom elements. Read the docs, they explain this transition clearly. Did I mean that you can use custom elements to encapsulate any kind of state or logic or interaction with drivers? No. Not even MVI is for "any kind of state or logic or interaction with drivers".

**Comment by matchu** [comment]
So we can only encapsulate MVI when working with the DOM? Huh. Okay.

**Comment by staltz** [comment]
Did I say DOM? MVI is an architecture for user interfaces. If you are interfacing with XHR, no you shouldn't use MVI. You can, but it's meant for that. But you can use MVI against a Canvas for instance, because that's UI.

**Comment by matchu** [comment]
Gotcha. So, if I want to do this sort of thing when rendering to Canvas, I should engineer the Canvas driver to have something analogous to the DOM driver's custom elements?

**Comment by staltz** [comment]
Yes, that's probably a good idea.

**Comment by staltz** [comment]
@matchu I added your no-nonsense definition of Cycle.js to the docs site: http://cycle.js.org/observables.html#what-is-cycle-core (force refresh to see it). Thanks :+1:
