### ISSUE TITLE
Programmatically focus input

### ISSUE THREAD

**Issue by OliverJAsh** [cyclejs/cycle-core#153]
I want to create an app with a button which, each time it is pressed, appends a new text input field to the document body and focuses it. This would require invoking `input.focus()` after the view has rendered. How does this fit into the cycle of MVI?

**Comment by staltz** [comment]
virtual-dom hooks.
One trick I use with Observable and hooks is to flatMap each "should focus" event to an Observable of just [true, null], and then the virtual-dom hook checks if the value given is not null, doing the side effect (`input.focus()`) only when not null. The reason why we emit null is to be safe in the presence of combineLatest et al. which remember past events.

**Comment by staltz** [comment]
To give some context, these are side effects and by default they should happen in a [driver](http://cycle.js.org/drivers.html). However, it is very convenient to express the vtree and the focus side effect together, so instead of a driver, we use virtual-dom hooks. There are other DOM-related side effects that can be easily put in a driver. For instance, a `preventDefault` driver that consumes an Observable of events which should be preventDefault()'ed, and does that in a subscribe.

**Comment by OliverJAsh** [comment]
Perfect, thanks!
