### ISSUE TITLE
Cycle.js "Game" Driver

### ISSUE THREAD

**Issue by WorldMaker** [cyclejs/cycle-core#155]
Pardon me if I leave some things I've been thinking about here in case anyone else is curious to maybe explore the idea as well. I've been thinking for a while it might be nice to play with an FRP game engine and HTML5 game engines are a big fad these days. Cycle would probably be a great base platform, so maybe it might be neat to try to build a Game-oriented driver. Of course, I'm sure this is simply a "nice to have" for Cycle and probably not an important thing to build anytime soon, but again maybe there is shared interest.

The requests/intents mostly straightforward and some of them can/would be shared with the DOM driver:

- Gamepad changes
- Mouse events
- Keyboard events
- Touch events
- Game "Heartbeat" timer observable (make sure the model updates at a relatively steady rate; in game dev often called an "update timer")
- Game "Render" timer to make sure that renders happen in a timely fashion (note that you might have to compete with the 60fps or bust crowd to get anything accepted as a "real" game engine)

It's the responses/view output/rendering pipeline that I haven't quite figured out what would be the best approach to potentially balance performance and ease of programming. A pro of direct canvas and WebGL work is that it can be a lot faster than the HTML DOM and you don't need a strong diff/patch library to get a reasonable output. On the other hand, a flipside con of the same is that you are expected to spit out every pixel, every frame, hopefully quickly. (In a way, the diff/patch moves to the model side: you want something high level enough that it is quick to render with high level drawing commands, but fast enough to easily and regularly build/update from your "heartbeat" timer.) I think that something awesome is certainly possible, I'm just not sure what that would be yet. Some of the obvious possible options:

- WebGL commands (these things are *so* imperative/procedural that you almost worry you'll have to wrap them in a giant monad Haskell/LINQ style, right?)
- Canvas commands (ditto)
- Some sort of Scene Graph (I haven't seen any strong well beloved options that I can see; lots decisions on how high level of a graph to be)
- "Raw Pixels", or more specifically functions of space to color (aka Shaders)

Regarding that last one, as ludicrous as it may sound at first, Gaëtan Renaudeau (@gre) is surprisingly contagious on the subject (example: his [Functional Rendering speech](http://greweb.me/2013/11/functional-rendering/)) and he is correct that Shaders are definitely the major Functional Rendering pipeline in graphics/games and GLSL is one of the web's most Functional languages. He's been doing some interesting and very performant things with GLSL over the last few years, and maybe there's an interesting way to build a Cycle driver that speaks/interacts with GLSL... That said I absolutely can't tell you if building a GLSL shader diff/patch is any crazier than building a WebGL/Canvas Monad, or even compromising on a Scene Graph that would reliably meet most people's needs for that matter and be easy for people to build good functional reactive models with...

Anyway, that's my half-baked idea. Other chefs are welcome to contribute thoughts/ideas.

**Comment by staltz** [comment]
That would be rad!
I myself thought of building a small game example with Cycle.js, but immediately thought how I was missing some good amount of game-related boilerplate (at least for sprites, e.g.). My game programming background is entirely 2D games, so I can't comment much on the 3D side, other than *maybe* would be good to use three.js in the game driver.

Anyway, I'd be happy to support this project if someone starts it.

**Comment by Widdershin** [comment]
I'm interested in using Cycle.js for a browser based game development tool I'm working on ([Helix Pi](http://www.helix-pi.net)). I think that creating a driver on top of a tool like [Pixi](https://github.com/GoodBoyDigital/pixi.js) would be ideal.

I had this idea after seeing Izzimach/react-pixi, which seems quite cool. An interim option might also be to use pH200/cycle-react as a Cycle driver so you could make use of react-pixi.

I like the idea of sticking with a virtualdom, even if it's at a sprite level.

**Comment by Frikki** [comment]
As a side note, in Web games, in particular, often styles of elements are calculated based on other elements, e.g., using `offsetParent` and `offsetLeft` and `offsetRight`. How does this translate in a virtual DOM?

**Comment by ivan-kleshnin** [comment]
> maybe would be good to use three.js in the game driver

three.js is ridiculously object oriented. Just look at this ashaming thread https://github.com/mrdoob/three.js/issues/2950

**Comment by WorldMaker** [comment]
I don't see a strong argument in that thread, Ivan. Also, object-oriented code can be intermixed with Cycle if some right, the goal would be to isolate state mutation in a similar way that virtual-dom isolates stateful HTML DOM objects.

On a slightly more constructive note, I was briefly looking at Babylon.js again. Like with most of the JS engines I've seen, I wish it were more modular, but it had some useful ideas and has been used for some big "real" games so I keep thinking I might try a deconstruction of the engine...

**Comment by Frikki** [comment]
ECMAScript is, per definition, oriented around objects; thus object-oriented. That you can do functional programming with objects doesn’t change that.

**Comment by Widdershin** [comment]
I've started building games in Cycle.js using https://github.com/Widdershin/cycle-animation-driver

SVG makes for a decent rendering medium, but I'm amazed at how suitable the DOM is for small games.

**Comment by ivan-kleshnin** [comment]
> ECMAScript is, per definition, oriented around objects; thus object-oriented. That you can do functional programming with objects doesn’t change that.

No. As long as language allows first-class functions and closures you can program in functional paradigm. Paradigms are not about languages. I wrote zero explicit loops and zero times used prototype machinery in my own code layers. So it's totally possible to avoid object-oriented approach an be happy. Your arguing is the same as "actually we all program in binaries" just because every programs gets to that level in some moment. No, we don't program in binaries. We program in the paradigm we're thinking in.

The problem with games is that C++ is still considered to be the main language for commercial games.
And C++ is contaminated with OOP to the "alarm" level. People coming from there need tons of time to purge their brains from that garbage. Some failed to do this at all.

**Comment by axefrog** [comment]
The term "Object Oriented" typically refers to the promotion of inheritance and polymorphism in a language's feature set. If you're arguing against careless mutability however, the reason games are primarily written using encapsulated objects is that the knowledge flows from the cutting edge at the top of the industry right down until it reaches the hobbyist, and cutting edge games have a tendency to need to extract every last bit of performance out of the hardware. This means that you end up having to work primarily with mutable state because you need fine-grained control over memory access, not just for managing allocation, but to ensure that you're not causing unnecessary CPU cache misses when accessing data structures; doing so can have a significant effect on performance. The end result is a whole lot of mutability in your code, that you ultimately end up trying to manage by wrapping things up in objects. Try writing a AAA game in a functional language and see how far you get, performance-wise. Granted you can go the "pure C" route, but then you end up with lots of structs grouping chunks of state together, and purpose-specific functions for managing the state, which really ends up just being a kind of simplified destructured class model.

**Comment by ivan-kleshnin** [comment]
@axefrog I agree with what you've said. My point is that maybe NOW is a perfect time to try writing games with newer concepts in mind. Because rock-solid peformance is a must for AAA games but not so much for Indie games, browser games, etc. Is RxJS too slow? What market can it satisfy? 
It's our task to verify!

**Comment by Widdershin** [comment]
Also, if you need the performance that mutability brings, it's not like
RxJS or Cycle enforces immutability. Currently working on a game in
Cycle.js, writing it with mutable state to start with.

**Comment by axefrog** [comment]
@Widdershin agreed, I have a small job I've been doing and the state management exists entirely behind a driver, which simply takes requests to mutate state, and emits an updated state model with each mutation, leaving the UI clean and stateless. I think learning what is ok to put behind the driver boundary is half the battle with this whole approach to application development.
