### ISSUE TITLE
Canvas Driver

### ISSUE THREAD

**Issue by bcoop713** [cyclejs/cycle-core#157]
I would like to create a canvas driver. I don't have too much experience with the canvas API, so I've been doing some research. 

I found a few javascript libraries for canvas interaction and creation, but I'm leaning towards going dependency free. 

http://fabricjs.com/
http://www.createjs.com/easeljs

Any thoughts?

**Comment by staltz** [comment]
You would need something comparable to virtual DOM. The way of building the view should be fully declarative, but canvas APIs and wrappers are normally imperative/mutable APIs.

**Comment by cgeorg** [comment]
[react-canvas](https://github.com/Flipboard/react-canvas) might be a good thing to look at for inspiration.

**Comment by HighOnDrive** [comment]
There are two approaches, immediate or retained. I would prefer the immediate because I have all my parameters abstracted into models on Firebase already, ready to be streamed to views. My app makes use of the Canvas API primitives together with Opentype.js. The Canvas element alone is powerful and has new functionality like the Path object, etc.

The retained approach involves creating a host of objects if you do not have proper models in place. I wrestled with the whole scene graph issue and learnt to abstract flexible models instead that can be streamed. However, the retained one React folks like is https://github.com/reactjs/react-art but I do not need it :)

**Comment by staltz** [comment]
If I would build this (and I might if time allows), I'd first make an unopinionated library similar to virtual-dom, but targeting canvas. Only then would I make the driver to wrap that library.

**Comment by axefrog** [comment]
Yeah I think you could easily create a hybrid retained/immediate mode driver where you don't represent high-level objects so much as sets of instructions that can be replayed. I think I am very likely to start work on this later today because the website I am developing for my current client has heavy canvas-drawing requirements.

**Comment by HighOnDrive** [comment]
Sounds interesting, might have some ideas here. Certainly have a use for a canvas.

**Comment by HighOnDrive** [comment]
There is an implementation of a canvas driver that wraps the pixi.js library here: https://github.com/eschwartz/cycle-pong

**Comment by eschwartz** [comment]
Thanks, @HighOnDrive. [Here's the (very simple) driver you were referring to](https://github.com/eschwartz/cycle-pong/blob/master/src/driver/pixi-driver.js)

> If I would build this (and I might if time allows), I'd first make an unopinionated library similar to virtual-dom, but targeting canvas.

Take a look at [jsondiffpatch](https://github.com/benjamine/jsondiffpatch) -- I think that will get you a good way torwards where you're going. If you can put together a structural representation of your view models, it should be pretty straightforward to map diffs in those view models to canvas operations (especially if you make use of a decent Canvas/Game library).

I started messing around with something like that for my pong game, but I decided my time was better spent wrapping my head around RxJS...

**Comment by staltz** [comment]
Thanks for pointing to jsondiffpatch!

**Comment by HighOnDrive** [comment]
@eschwartz jsondiffpatch looks great! 

I have the view models but am not really needing a full blown graphic scenegraph library at this time. The view models serve this purpose for me so I just want to draw to the standard canvas element, which is just a image.

Would a driver be required when rendering to a standard canvas? The virtual-DOM would not diff the drawing but maybe if I track and set a dirty state on the canvas node it might?

**Comment by HighOnDrive** [comment]
I’ve been able to think things through further and agree that I will need a canvas driver no matter if I use a retained or immediate approach to rendering. I need a bit more to go on than just adopting drivers as a Cycle pattern because it is the in thing to do. 

Turns out it is a combo of how Cycle loops it’s driver processes, keeps main pure, interacts with the virtual-DOM and so on. I just wanted to know why whenever I do things in Cycle an extra driver step is often required. As long as it is purposeful then I’m good to go :-)

So the verdict is that a canvas driver is required for both immediate and retained rendering scenarios. In this case it would make sense to create a universal canvas driver for Cycle, that can interface with the standard HTML5 canvas element by default and then also any other retained/scenegraph related graphic API out there if desired?

Then a developer could have a base to work with and not have to figure out how to interface with graphics within Cycle over and over. They could then just customize a stock ``cycle-canvas-driver`` further, depending on their use case and and any optional 2D/3D API they might choose.

**Comment by Frikki** [comment]
@HighOnDrive What do you mean, "keeps main pure"? `main()`, because it takes in the world as sources, produces side effects, and is, thus, not pure at all, i.e., there is no guarantee that `main()` produces the same result every time.

**Comment by staltz** [comment]
@Frikki if you provide the same inputs, it should help put the same results.

**Comment by Frikki** [comment]
@staltz Surely, but there is no guarantee; thus, not pure.

**Comment by staltz** [comment]
Does anything in JavaScript have a guarantee?

**Comment by Frikki** [comment]
@staltz Good question. In a perfect environment, yes. But since JavaScript relies on other software, and ultimately, on hardware, then no. What I was referring to was the idea of pure functions.

**Comment by staltz** [comment]
Then neither is `x => x * 2` a pure function?

**Comment by Frikki** [comment]
Yes, in the sense of pure functions, it is, because the function always evaluates the same result given the same argument.

**Comment by staltz** [comment]
And why can't a `main()` ever do the same?

**Comment by Frikki** [comment]
It can, if you don’t feed it the world, i.e., drivers. The drivers can cause all kinds of unpredictable side effects; thus, the main result may not evaluate the same on the same argument(s) given.

**Comment by HighOnDrive** [comment]
Hey dudes, just seeing all this talk of purity after watching RxJS vids all day and recovering with a late night deep trance jam out on the guitar, whats up! LOL

By keep ``main()`` pure I only meant that it has it's specific task and then ``run()`` handles the actual looping, which might not be looping in a sense at all, because observables don't do squat unless they are subscribed to and there are events to react to, so they are not just orbiting. At least that is my current understanding.

I'm just thinking further on that universal cycle-canvas driver now :smile:
