### ISSUE TITLE
Make Rx a peer dependency

### ISSUE THREAD

**Issue by teohhanhui** [cyclejs/cycle-core#174]
Is there any good reason why the user shouldn't be able to just use any RxJS version (perhaps add it as a [peer dependency], which IMO would be more correct)?

What's the need / benefit of having `cycle-core` exposing `Rx`? I don't buy the "shortcut" argument when it doesn't make any real difference:

`import {Rx} from '@cycle/core'`
vs.
`import Rx from 'rx'`

[peer dependency]: https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by teohhanhui** [comment]
I've had some discussion on this at axefrog/cycle-router5#7

**Comment by staltz** [comment]
I'll consider alternatives, you can add more suggestions (beyond peer dependencies if can think of anything else). The reason why it has been inside Cycle is so that people don't need to worry about setting up, they could just install Cycle core and be ready. But your experience is an indicator that something can be done better.

**Comment by teohhanhui** [comment]
Perhaps you can have a special build with RxJS built in (e.g. similar to the console build).

**Comment by teohhanhui** [comment]
But then again, nothing really stops me from using a different version of RxJS now, assuming there won't be interop issues between `Observable`s created by the different versions.

**Comment by staltz** [comment]
True, but space usage would be a problem.

**Comment by Frikki** [comment]
Ever heard of the adapter pattern? It let’s your code be independent of libraries.

The problem is that when you depend your code on, for example, RxJS, should you decide to drop RxJS then you need to rewrite all your own source that made a tight coupling to the library. In OO, we would tackle this by defining our own interfaces and then adapt any library APIs that we use to our own interfaces.

**Comment by staltz** [comment]
Nah, let's not do that. I was thinking we could follow what Yolk did, but then I checked again, and they reverted from rx-as-peer-dependency to rx-built-in, lol. https://github.com/yolkjs/yolk/issues/12

**Comment by teohhanhui** [comment]
> In the case of using Yolk with Webpack, however, you deliberately have to require Rx before requiring Yolk for the first time - that sucks.

That's a problem which can and should be solved in `webpack` configuration (and in my case, `jspm` package override). Not really a valid argument against this.

**Comment by gaearon** [comment]
What I usually do in these case:

* Make this thing a peer dependency
* Put it in `exports` in Webpack config (or equivalent), so UMD build assumes people already make it available somehow, and doesn't try to bundle it

This puts user in control. Yes, you are forcing user to include Rx themselves if they use a global build, but I think it's a fair decision because they *might* already use global Rx and you don't want them to bundle it twice.

**Comment by staltz** [comment]
Sounds reasonable. 

> Yes, you are forcing user to include Rx themselves

This is the only problem, but on the other hand, we already force people to install multiple packages, **at least** `@cycle/core` and `@cycle/dom`.

**Comment by gaearon** [comment]
Exactly. Also, people using UMD today are either

* running legacy large app whose build workflow is hard to change — not likely in case of Cycle
* want to cut production build times — they'd probably be happy using standalone Rx anyway

**Comment by secobarbital** [comment]
:+1: This eliminates [the need to version cycle-core just to update rx](https://github.com/cyclejs/cycle-core/pull/175) and many drivers can peer-depend on ```rx``` instead of ```@cycle/core```.

**Comment by staltz** [comment]
Doing this right now...

**Comment by staltz** [comment]
Done in v5.0.0
