### ISSUE TITLE
Dataflow components breaks composition

### ISSUE THREAD

**Issue by gyzerok** [cyclejs/cycle-core#192]
I know folks, that you all hate React here, but try to read this with open mind.

What is one of the best features in React is the ability to build truly composable interfaces. Its not a secret that this is because of manipulating simple DOM tags and Components in the same way.

As I can see from `todomvc` and Gitter chat Cycle want to separate DOM elements and Components semantically. Hm, not a problem. The problem is it leads to the huge incidental complexity. Just to operate on items clicks in a list I need to create proxy and do a bunch of non-trivial staff (@staltz do you remember your talk when you showing example with open file in Java and same in Python? Now you can do it with Cycle and React :D). While `todomvc` should display how awesome your technology is, Cycles one looks like "I do not want to see it again".

I really like Cycle with its idea of explicit user events and explicit component events. Its awesome. But dataflow components looks like reinventing the wheel.

So I'm kindly ask you to investigate more before introducing your idea.

**Comment by Frikki** [comment]
> Dataflow components breaks composition

In which way? Dataflow components are functions, how does a function break composition?

> Cycle want to separate DOM elements and Components semantically... The problem is it leads to the huge incidental complexity.

A dataflow component does not necessarily have a DOM representation. I have not seen any "huge incidental complexity" whatsoever. Do you have an example?

> Just to operate on items clicks in a list I need to create proxy and do a bunch of non-trivial staff

No, you don’t need to do that. *TodoMVC* implements a clever pattern that allows items to control their own behavior in orchestration with the list and local storage. This pattern can seem complex, but it is definitely not a required pattern for operating on item clicks in a list.

> dataflow components looks like reinventing the wheel

How is that? What do they explicitly reinvent?

**Comment by staltz** [comment]
@gyzerok Thanks for pointing it out. I like receiving criticism on Cycle.js API, that's how we evolved the API over the last year. You should see Cycle 0.1.0 or so, it was horrible compared to what we have now. And I'm taking your feedback seriously now too.

Interesting, though, that you are answering yourself already. We cannot follow the React-like component model because we are trying to stay with magic-less JS only.

We cannot get this

> @gyzerok Its not a secret that this is because of manipulating simple DOM tags and Components in the same way.

because of this

> @gyzerok I really like Cycle with its idea of explicit user events and explicit component events. Its awesome.

> The problem is it leads to the huge incidental complexity.

Lack of magic isn't necessarily incidental complexity. Incidental complexity is when we add additional unnecessary abstractions/concepts on top. Framework magic are shortcuts that make code become implicit.

We could add a lot of magic in Cycle.js, but one of the key selling points with Cycle.js is that everything is just explicit JS and Observables. We don't want to lose that. 

On the other hand, what you saw with todomvc was to be honest the most advanced use case of Cycle.js: dealing with dynamic lists where each item is an advanced component. So todomvc Cycle is not the most representative of usual Cycle.js apps. That said, the technique we used there isn't really *hard*, the proxy technique takes just 2 more lines of code actually. (by the way, I recommend you look at the branch `auto-scope` which has the most up-to-date code, actually in better shape than what is in `master`)

And we're not done there. Issue #170 is one strong idea of how to make those use cases easier. The heart of the issue is: coding in Cycle.js is simple as long as the dataflow graph is a DAG (Directed Acyclic Graph). If there is a small cycle in the dataflow graph, then we need the proxy technique or #170. There aren't yet any docs about it, but the technique is rather simple once you learn it.

If you want to help make Cycle.js better, whenever you find something that's not so great, let us know how could we do better, by asking yourself this question: "what would be the perfect API for this use case? Can I give an example snippet of that?"

**Comment by staltz** [comment]
I don't know what to do with this issue because it's just a discussion. Definitely dataflow components don't break composition. You can compose as freely as you want. Maybe the title can be renamed.

**Comment by gyzerok** [comment]
@staltz Okey, lets close it for now. I'm gonna wait for documentation on cycle nested first and try to understand it better.
