### ISSUE TITLE
Why not use event callbacks?

### ISSUE THREAD

**Issue by ccorcos** [cyclejs/cycle-core#201]
Its an interesting choice how drivers work in Cycle. I'm curious why you didn't stick with the whole "callback" style of registering events. This would make it easier to build drivers and to integrate with other libraries. 

I think this example maintains the spirit of Cycle, but allows you to use React (and React Native) and entirely deals away with the the issue of isolation (isolateSink and isolateSource).

```js
import {stream, scan} from 'flyd'
import lift from 'flyd/module/lift'
import h from 'react-hypersrcipt'

const counter = (props$) => {
  const action$ = stream()
  const state$ = scan(add, 0, action$)
  const inc = () => action$(+1)
  const dec = () => action$(-1)
  const view = (props, state) => {
    return h('div', props, [
      h('button', {onClick: dec}, '-'),
      h('span', state),
      h('button', {onClick: inc}, '+')
    ])
  }
  return {
    html$: list(view, props$, state$),
    count$: state$
  }
}
```

The way the current DOM driver works (binding actions before creating the DOM), makes me think that they're may be certain dynamic interfaces that couldnt be created.

Anyways, I'm curious about your thoughs on this decision.

**Comment by TylorS** [comment]
@ccorcos Hello, thanks for your interest in Cycle.js

This was a very conscious decision that was made, as it separates your view logic from your event logic. We believe this to be a better pattern an easier to reason about. Introducing event handlers in your markup is a strict coupling between the two. Avoiding strict coupling is something we generally try to avoid.

> This would make it easier to build drivers and to integrate with other libraries.

I'm not sure why you believe drivers to be difficult to create, or why you believe it's difficult to integrate with existing libraries? We are a young project with a small community, simply many integrations have not happened yet.

> The way the current DOM driver works (binding actions before creating the DOM)

The first part is not quite true. The DOM driver uses event delegation. It attaches event listeners to the root element supplied to `makeDOMDriver('#rootElement')` and uses filters and other techniques to properly match the events to the right places, and are connected before updating the view. 

The order in which we write it because of this seems to be very fluid (to me). User events -> model -> view. Or in other words,"What does my application/component allow the user do?" -> "How does that affect the state of my application?" -> "How do I represent my new state on the screen for the user?"

>  makes me think that they're may be certain dynamic interfaces that couldnt be created.

I'm curious what interfaces you refer to here? We're always looking for ways to improve.

**Comment by staltz** [comment]
> Why not use event callbacks?

Very simple to answer: because user events are read effects, and they should come through sources, **not** in the form of callbacks on sinks (meant only for write effects). This is super important for maintaining dataflow properties in Cycle.js.

> I think this example maintains the spirit of Cycle, but allows you to use React (and React Native) and entirely deals away with the the issue of isolation (isolateSink and isolateSource).

We are able to use React (Native) already in Cycle.js, because we postpone attaching event callbacks. See https://github.com/cyclejs/cycle-react-native as an example.

The snippet your wrote looks a lot like Yolk.js: https://github.com/yolkjs/yolk. Check it out if you prefer that approach. When it comes to Cycle.js, we're pretty sure we want user events separate from view.

Thanks for the conversation.

**Comment by ccorcos** [comment]
> why you believe it's difficult to integrate with existing libraries?

I just don't understand how to you connect `drivers.DOM.select('input').events('click')` to the input thats eventually returned to the DOM driver. It seems pretty challenging or littered with mutations. Take React for example -- how does the event handler get injected into the vdom before its rendered?

> I'm curious what interfaces you refer to here?

Imagine you are creating an "app-builder" app that has a bunch of drag and drop components to build little web apps (kind of like Interface Builder in Xcode). So you represent an entire application with a static data structure, and you compute the application ui using that data structure.

So suppose a user drags a div into the app workspace and then wants to add a "click" event to to trigger something else. With cycle.js it doesnt seem like you can dynamically add or remove event listeners like that. In order for this to work, every div in my app-builder app would need to bind any event handlers that user may want to use. Was that too contrived or does that make sense?

> The snippet your wrote looks a lot like Yolk.js

Interesting, you're right. I've never seen that. I'm really just trying to get a good understanding of Cycle.js vs Elm Architecture. Elm makes it trivial to build a time-traveling debugger but its has come performance concerns. Cycle.js looks like it has great performance, but doesnt offer quite as much introspection into your running program since the state is littered throughout in isolated places using `stream.scan`. Would you say thats a reasonable assessment?

**Comment by gaearon** [comment]
>I just don't understand how to you connect drivers.DOM.select('input').events('click') to the input thats eventually returned to the DOM driver. It seems pretty challenging or littered with mutations. Take React for example -- how does the event handler get injected into the vdom before its rendered?

I'm not a Cycle expert but I wanted to make clear that even React does not actually “inject handlers into vdom”. It is usually bad for performance to attach many event handlers, so under the hood React just *registers* component handlers in a map by the internal component ID, and only sets up a single event handler at the root of React hierarchy. This is similar to the event delegation approach that has long been used in Backbone and jQuery. I think in some cases React might actually subscribe to the node in question (depends on the event and browser quirks) but more often *I think* (it's best if you verify!) it subscribes to the root node.

**Comment by ccorcos** [comment]
Interesting. So you're saying, in concept, that React might just register a 'click' handler on the body, and then as an even bubbles up, it will interpret the event and dispatch a synthetic event for some div or button on the page?

**Comment by gaearon** [comment]
Yeah, I think this is pretty much what React does. In addition it normalized synthetic bubbling behavior across browsers to match the spec.

**Comment by staltz** [comment]
Nowadays Cycle DOM also does event delegation.

**Comment by devinrhode2** [comment]
Would love a cycle api that works something like the following:
dom.registerEventHandlers({
  dec() {
  }
  inc() {
  }
})

and you can return dom like this:
<button onClick={inc}>+</button>

registerEventHandlers is basically sugar over the existing setup. Instead of doing select('.className').on('eventName').call(eventHandler), registerEventHandlers would search the dom for event handler name attributes, and then register the specified function name for the specified event.

This frees up the className attribute to be used just for css, and draws a much more explicit connection between the view to event handlers.

**Comment by bloadvenro** [comment]
So this will silently "fail":

```
    a(".link", {
      props: {
        href: "/signup",
      },
      on: {
        click: () => alert(data),
      },
    }, "Click me!")
```

Right?

I was confused when tried to make it work :)

**Comment by jvanbruegge** [comment]
@bloadvenro The event listener callback module is not used by default. You can pass an array of snabbdom modules to the DOM driver

But why would you actually want to use this? It wont work with the rest of the DOM driver.

**Comment by bloadvenro** [comment]
@jvanbruegge Thank you)

I actually didn't know how to do it right. I started working with CycleJS only recently.

**Comment by bloadvenro** [comment]
@jvanbruegge 
> But why would you actually want to use this? It wont work with the rest of the DOM driver.

I tried to implement input normalization inside view function. The piece of code above is just a quick test.
