### ISSUE TITLE
DOM, multiple click-events when a single event should be returned

### ISSUE THREAD

**Issue by iambumblehead** [cyclejs/cycle-core#208]
Hi,

DOMDriver from @cycle/dom returns multiple click-events when a single event
should be returned.

Expected behaviour is that a single event is returned for a single click.

The virtual node looks like this:
```javascript
label('.cycvideo_bttnplay', {for : 'uidplay'}, [
  span('.cycvideo_bttnplay-primary'),
  button('.cycvideo_bttnplay-button #uidplay', {
    type : "button"
  })
]));
```

The button is hidden with this style:
```css
.cycvideo_bttnplay-button {
  display:none;
}
```

And the DOM select looks like this:
```javascript
DOM.select('#uidcycvideo_bttnplay').events('click').map(ev => ev).map(n => {
  console.log('play', n.target); return 'play';
})
```

When clicking this play node, two messages are logged to console:
```
play <span class="cycvideo_bttnplay-primary">
play <button class="cycvideo_bttnplay-button" id="uidplay" type="button">
```

You can see this in the test repository here:
https://github.com/iambumblehead/cycvideo
https://github.com/iambumblehead/cycvideo/blob/master/src/js/cycvideo_bttnplay.js#L10-L16
https://github.com/iambumblehead/cycvideo/blob/master/public/bundle.css#L38-L40
https://github.com/iambumblehead/cycvideo/blob/master/src/js/cycvideo.js#L38

Thank you

**Comment by laszlokorte** [comment]
you should use `ownerTarget` or `currentTarget` instead of `target` because cycle dom uses event delegation.

Without having looked into your code it looks like a hot/cold observabl issue:
Putting `log()` calls into a `map()` (or other transformations) and then counting the output in the console is not correct. 2 lines written to the console does not indicate that the event was really triggered multiple times but only that the `map()` was executed multiple times (once per subscriber, not once per event)

**Comment by iambumblehead** [comment]
@laszlokorte thanks for the response. There is only one subscriber to this event. Removing the button's element definition in the vnode results in a single event call.

using currentTarget shows the label element in the console.

**Comment by laszlokorte** [comment]
Btw `'.cycvideo_bttnplay-button #uidplay'` you have a space there between the class name and the id. I am not sure if that is correct.

**Comment by laszlokorte** [comment]
Then you have a label around the button. Could it be that the click one the label triggers the seconds click on the button? Ie that it is a pure DOM problem not a cycle one.

**Comment by iambumblehead** [comment]
@laszlokorte clicking the label should not result in click events at the button. I removed the space you mentioned but it did not affect any change in the results.

**Comment by laszlokorte** [comment]
I just tested it in pure html/js: clicking a label triggers an additional click on the button it belongs to.
Because your label contains the button the click triggered on the button will then bubble up to the label.

You are binding your listener to the label so for me it is pretty obvious that you get two clicks:
the original click on the label and then the click on the button which bubbles up to the label.

**Comment by iambumblehead** [comment]
@laszlokorte thank you --I should have done the diligence there but felt sure that I knew what the expected behaviour should be --thank you!
