### ISSUE TITLE
Need suggestion on writing in ramdajs syntax

### ISSUE THREAD

**Issue by geohuz** [cyclejs/cycle-core#209]
I just learned ramdajs functional programming library and trying to convert the checkbox example into ramdajs syntax, like so:

```
import R from 'ramda'
import Cycle from '@cycle/core';
import {makeDOMDriver, div, input, p} from '@cycle/dom';

function main(sources) {
  let  _output = function(toggled) {
    return div([
          input({type: 'checkbox'}), 'Toggle me',
          p(toggled ? 'ON' : 'OFF')
        ])
  }
  let exp =
    R.compose(
      R.map(_output),
      R.curry(startWith(false)),
      R.map(R.prop('target.checked'))
    )

  const sinks = {
    DOM: exp(sources.DOM.select('input').events('click'))
  } 
  return sinks;
}
```

But I was given the following error:

```
ReferenceError: Can't find variable: startWith
```

Is there any suggestion on this problem? Or doing so is not encouraged? I was loving ramda's approach to be more 'functional' way ;-)

**Comment by erykpiast** [comment]
Because it seems to be not defined in your scope :) If you wish to call method of `Observable` that way, look at `invoker` function in Ramda. But I'm not sure if it does make sense. In case of more common operators (like `filter`, `map`, `reduce`) look at `transduce` method of `Observable`. It's the thing thanks to which you can use functions from Ramda (and not only) with `Rx`.

**Comment by staltz** [comment]
Because this isn't really about Cycle Core, I'll have to close this issue, sorry
