### ISSUE TITLE
How to create components depending on initial options?

### ISSUE THREAD

**Issue by FunkMonkey** [cyclejs/cycle-core#211]
I ran into a situation, where I want to create a component based on the first element of a source stream.

Consider this example, where I get an options object from some (asynchronous) source. Based on the option `renderA` I either create `ComponentA` or `ComponentB`. This is my current solution:

```js
function main( sources ) {
  
  const initialOptions$ = sources.options$.first();
  const sinks$ = initialOptions$.map( options => {
	if( options.renderA )
		return ComponentA( sources );
	else 
		return ComponentB( sources );
  } );
  
  const cache$ = sinks$.replay( null, 1 );
  cache$.connect();
  
  return {
	DOM: cache$.flatMapLatest( sinks => sinks.DOM ),
	HTTP: cache$.flatMapLatest( sinks => sinks.HTTP )
  };
}

Cycle.run( main, {
  DOM: makeDOMDriver('#main-container'),
  HTTP: makeFetchDriver(),
  options$: makeSomeDriver()
} );
```

My current idea is to use `flatMapLatest` to return the correct sinks. Unfortunately this means that I have to use `replay` as a cache when having multiple output streams instead of simply using `sinks$.flatMapLatest`. Without the cache the creation of the components will happen multiple times (once for every subscription to `sinks$`).

Is there a better solution to this problem?

Thanks a lot. Cycle is really a great library. Really changed my way of thinking :)

**Comment by staltz** [comment]
Unfortunately, not, because of the lazy and regenerative nature of RxJS Observables. If you want that behavior, you need a `connect()` somewhere.

Another option is to build `sinksA` and `sinksB`, then use the `options` to select either `sinksA` or `sinksB`, but you still need a `connect()`.

In issue #196, see how we are adapting Cycle.js to use other stream libraries than Rx.
