### ISSUE TITLE
Page Routing, pushState/popState, and <a href>

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#37]
Refer to the discussion in #32 and #51

Reference https://github.com/rackt/react-router/blob/master/docs/guides/overview.md

**Comment by staltz** [comment]
Suggested routing helpers:
```javascript
var AppView = Cycle.createView(function (model) {
  return {
    vtree$: model.get('route$')
      .map(route => Cycle.switchRoute(route, {
        '/posts': {
          '/': h('posts-home-page'),
          '/new': h('create-post-page'),
          '/:id': {
            '/': id => h('post-page', {attributes: {id: id}}),
            '/edit': id => h('edit-post-page', {attributes: {id: id}})
          }
        }
      }))
  };
});
```

**Comment by asafyish** [comment]
+1

**Comment by agilgur5** [comment]
+1

**Comment by WorldMaker** [comment]
I've got an interesting work in progress in this area. I got stuck in the middle of finishing the proof of concept from a JSPM issue (`virtual-dom` dependency of a dependency to `es5-ext` which uses funny CJS folder name that browsers don't like and JSPM possibly needs to work on or `virtual-dom` should rely on friendlier polyfills, IDK)...

Anyway, I thought maybe I should document some of this before GenCon so that I remember it after GenCon (and maybe someone wants to play with it while I'm away). I smashed a couple of ideas together and ended up with a different, but perhaps more interesting approach to routing (and maybe other things). I started partly with this [article where the main takeaway was using JSON documents to enumerate examples of all the potential states of a UI design](http://rauchg.com/2015/pure-ui/) and realizing with a little bit of extra on top you can have your declarative cake and it eat it too with some sort of simple RegEx-like State object pattern matching. Searches turned up [object-pattern](https://github.com/xaviervia/object-pattern) and I've been slowly gluing the pieces together into what I think will be a compelling whole. `object-pattern` is cool because it handles URL-like routing, but can also handle a variety of other JSON pattern matching, in JSON, again presumably including routing, but also more things.

Because no JS project is real without some silly name and because I got trapped into thinking that a project using such a routing system could be used for everything from say page routing to basic state-based template routing (use this template if the widget state is "edit" and this template if the widget state is "view"), to a bunch of other possibilities and it could be nested quite a bit and thus "turtles all the way down". So the cornerstone here is [turtle-factory](https://github.com/WorldMaker/turtle-factory).

So `turtle-factory` is a simple LISP-like macro for view composition written in ES6 (well, TypeScript, but ES6) that takes in a simple JSON object and spits out a simple `export default function view(state)` using object pattern and ES6 imports. I think it's pretty neat because other than a dependency on `object-pattern` (and implicitly on SystemJS), it's relatively pure and makes very few assumptions about what sort of input/output it is working with. (ES6 loader plugins and ES6 template strings make for a surprisingly decent macro-writing experience, which is nifty.)

My plan, once the JSPM issue is sorted out, is take `turtle-factory` and [system-jade-virtualdom](https://github.com/WorldMaker/system-jade-virtualdom) (a simple ES6/SystemJS plugin for taking in Jade templates and spitting out virtualdom views) and build a [turtle-zoo](https://github.com/WorldMaker/turtle-zoo-cycle) with Cycle to show off the concept. (Zoo, rather than Gallery, because the idea would be to have "live" views, based upon the metadata in the JSON documents... Sorry, more cutesy JS naming because it's a hard habit to break.)

Sorry about the infodump, but maybe someone will find it interesting/useful to think about while I work on finishing up the proof of concept, aka the zoo. The JSPM thing bugs me so much for getting in my way, because this all currently hinges on SystemJS. Having not finished my proof of concept I also have no idea how well this would perform.

I guess to show an example of what I'm thinking, for your CycleJS view:

```js
import turtleView from 'router.json!turtle-factory';

export default function view(state$) {
    return state$.map(turtleView);
}
```

Then you might have a `router.json` which might look something like:

```js
{
  "name": "My Posts Router",
  "turtles": [
    {
       "name": "Create New Post",
       "pattern": "route:/posts/new",
       "require": "create-post-page.jade!jade-vd",
        "examples": [{
            "route": ["posts", "new"]
         }]
    },
    {
       "name": "Edit Post",
       "pattern": "route:/posts/<number>/edit",
       "require": "edit-post-page.jade!jade-vd",
        "examples": [{
            "route": ["posts", 12, "edit"]
         }]
    },
    {
       "name": "View Post",
       "pattern": "route:/posts/<number>",
       "require": "post-page.jade!jade-vd",
        "examples": [{
            "route": ["posts", 12]
         }]
    },
    {
       "name": "Posts Home",
       "pattern": "route:/posts",
       "require": "posts-home-page.jade!jade-vd",
        "examples": [{
            "route": ["posts"]
         }]
     }
  ]
}
```

Yeah, it's a little verbose, but the idea/goal is you could have a nice zoo for an interesting design time experience... Maybe someone else will find it interesting, too.

**Comment by staltz** [comment]
@WorldMaker interesting! 

Would this
```js
"pattern": "route:/posts/<number>/edit",
"require": "edit-post-page.jade!jade-vd",
```
mean that `edit-post-page.jade` gets `number` as a value to use in the template?

**Comment by WorldMaker** [comment]
That's just object-pattern syntax for a tour check. At the moment turtle-factory doesn't go any state transformation, it just passes the state directly to the required view function, so the jade template would worst case would use `route[1]` to grab that id, presumably (or the model to also store it somewhere more interesting in the state object). I researched, briefly, possibilities for declarative object transformation, but didn't find any options I liked and for now I see the burden being in defining the model function to produce the state you want for your templates, or chaining your requires in useful ways. Because that require is just any ES6 module that returns a function of one argument you could require for instance "edit-post" and in edit-post.js:

```js
import template from 'edit-post-page.jade!jade-vd';

export default function view(state) {
  state["post_id"] = state.route[1];
  return template(state)
}
```

That's the composition pattern in play, any ES6 module can be required that has that `export default function view(state)`, which is also what the turtle-factory which is why you could nest them and maybe instead of require "edit-post-page.jade!jade-vd" you have a require for "edit-post.json!turtle-factory" that routes/pattern-matches based on something like "post_type: blog" versus "post_type: photo" for different editing experiences.

**Comment by WorldMaker** [comment]
Sorry for typos, sent from my phone. Also, I say ES6 module and use that syntax to describe the concept, but SystemJS happily loads CJS and AMD formats to. The module pattern in CJS would be something like:

```js
function view(state) {
  // ...
}

module.exports = view;
```

**Comment by staltz** [comment]
This issue has been superseded by #159.
